# Projects Configuration
# 
# This file defines all projects displayed on the interactive map.
# 
# To add a new project:
# 1. Add it under the appropriate province in 'provincial' or under 'national'
# 2. Include at least the 'name' field
# 3. Optionally add 'category' field (divulgacion-general, educativos-institucionales, restauracion-conservacion)
#    If not specified, defaults to 'divulgacion-general'
# 4. Add any social media links (instagram, facebook, x, web, contacto, etc.)
# 
# To add a new social network:
# 1. Simply add a new field to any project (e.g., youtube: "...")
# 2. The system will automatically recognize and display it
# 
# Projects without any social media links will not be displayed on the map.

# Provincial projects organized by province name
provincial:
  "Buenos Aires":
    - name: "Nativas bonaerenses"
      category: "divulgacion-general"
      instagram: "www.instagram.com/nativas.bonaerenses"
      contacto: "nativasbonaerensess@gmail.com"
    
    - name: "Flora del Sistema de Tandilia"
      category: "divulgacion-general"
      instagram: "www.instagram.com/flora.tandilia"
    
    - name: "Flora de Punta Alta"
      category: "divulgacion-general"
      instagram: "www.instagram.com/flora.de.punta.alta"
    
    - name: "Flora Nativa Bahía Blanca"
      category: "divulgacion-general"
      instagram: "www.instagram.com/floranativabb"
      facebook: "www.facebook.com/floranativabb"
      web: "https://floranativabb.com.ar"
      contacto: "floranativabb@gmail.com"
    
    - name: "Nativas de Del Viso (Pilar)"
      category: "divulgacion-general"
      instagram: "www.instagram.com/nativasdelvisopilar"
      facebook: "www.facebook.com/nativasdelviso"

    - name: "Planta y Canta (Lanús)"
      category: "educativos-institucionales"
      instagram: "www.instagram.com/plantaycanta"
      facebook: "www.facebook.com/plantaycanta"
      contacto: "afrostudio@hotmail.com"

  "Catamarca":
    - name: "Flora Catamarqueña"
      category: "divulgacion-general"
      instagram: "www.instagram.com/floracatamarquena"
    
    - name: "Nativas de las Sierras (Catamarca y Córdoba)"
      category: "divulgacion-general"
      instagram: "www.instagram.com/flora.serrana"

  "Chubut":
    - name: "Nativas de Chubut"
      category: "divulgacion-general"
      instagram: "www.instagram.com/nativas.chubut"

  "Córdoba":
    - name: "Nativas de Córdoba"
      category: "divulgacion-general"
      instagram: "www.instagram.com/nativascordoba"
    
    - name: "Nativas de las Sierras (Catamarca y Córdoba)"
      category: "divulgacion-general"    
      instagram: "www.instagram.com/flora.serrana"

  "Corrientes":
    - name: "Nativas de Corrientes"
      category: "divulgacion-general"
      instagram: "www.instagram.com/nativasdecorrientes_arg"
  
  "La Pampa":
    - name: "Senderos interpretativos de flora autóctona \"Paseo de Las Tunas\" y \"Los Caldenes\" (Guatraché)"
      category: "restauracion-conservacion"
      telefono: "+54 9 11 3158-3447"

  "Mendoza":
    - name: "Flora Mendocina"
      category: "divulgacion-general"
      instagram: "www.instagram.com/flora.mendocina"
      facebook: "www.facebook.com/flora.mendocina"
    
    - name: "Nativas Mendocinas"
      category: "divulgacion-general"
      instagram: "www.instagram.com/floranativamendocina"

    - name: "Suma Nativas (Potrerillos)"
      category: "restauracion-conservacion"
      instagram: "www.instagram.com/sumanativas"
      facebook: "www.facebook.com/sumanativas"
      web: "https://sumanativas.wordpress.com"

  "Misiones":
    - name: "Flora Misionera"
      category: "divulgacion-general"
      instagram: "www.instagram.com/floramisionera"

  "Río Negro":
    - name: "Flora Nativa de Río Negro"
      category: "divulgacion-general"
      instagram: "www.instagram.com/flora.nativa.rn"

  "Salta":
    - name: "Nativas de Salta"
      category: "divulgacion-general"
      instagram: "www.instagram.com/nativasdesalta"
    
    - name: "Nativas salteñas"
      category: "divulgacion-general"
      instagram: "www.instagram.com/saltanativas"

  "San Luis":
    - name: "Nativas de San Luis"
      category: "divulgacion-general"
      instagram: "www.instagram.com/nativasdesanluis"

  "Santa Cruz":
    - name: "Fundación ANFIBIA (El Chaltén)"
      category: "restauracion-conservacion"
      instagram: "www.instagram.com/fundacionanfibia"
      facebook: "www.facebook.com/SoyAnfibiaChalten"

  "Santa Fe":
    - name: "Proyecto escolar \"Sueños bajo chañares\" (Chañar Ladeado)"
      category: "educativos-institucionales"
      instagram: "www.instagram.com/escuelasanmartin213"

  "Santiago del Estero":
    - name: "Nativas de Santiago del Estero"
      category: "divulgacion-general"
      instagram: "www.instagram.com/nativas_santiagodelestero"

  "Tierra del Fuego":
    - name: "Flora de Tierra del Fuego"
      category: "divulgacion-general"
      instagram: "www.instagram.com/flora.de.tierradelfuego"
      facebook: "www.facebook.com/floratdf"

  "Tucumán":
    - name: "Nativas tucumanas"
      category: "divulgacion-general"
      instagram: "www.instagram.com/nativastucumanas"
    
    - name: "Fundación Forestar"
      category: "restauracion-conservacion"
      instagram: "www.instagram.com/fundacionforestar"

# National-level projects (Argentina-wide)
national:
  - name: "Helechos y Licófitas de Argentina"
    category: "divulgacion-general"
    instagram: "www.instagram.com/helechosylicofitasdeargentina"
    x: "https://x.com/helechylicofarg"
    contacto: "helechosylicofitasdeargentina@gmail.com"
  
  - name: "Sociedad Argentina de Botánica"
    category: "divulgacion-general"
    instagram: "www.instagram.com/socargbot"
    x: "https://x.com/sabotanica"
    facebook: "www.facebook.com/sabotanica"
    web: "https://botanicaargentina.org.ar"

  - name: "Flora Vascular Argentina (Instituto Darwinion)"
    category: "divulgacion-general"
    instagram: "www.instagram.com/instituto_darwinion"
    web: "http://www.floraargentina.edu.ar"

  - name: "Me UNO al monte (juego de cartas de flora y fauna argentina)"
    category: "educativos-institucionales"
    instagram: "www.instagram.com/meunoalmonte"
    web: "https://www.meunoalmonte.com"
    contacto: "meunoalmonte@gmail.com"
